### PR TITLE
Fix type mismatch for cardValidCallback

### PR DESCRIPTION
**Pull request by imcyee**
Before this, callback is made by lambda, but it failed to infer the type and complain about type mismatch, required Interface CardValidCallback. This pull request is to explicitly add the interface

### CODE REVIEW

**Comment by NicholasBertazzonAga** [comment]
Going to review it soon even tho I haven't had any problems with android

**Comment by NicholasBertazzonAga** [comment]
Exactly, which version of Kotlin does your project use?

**Comment by imcyee** [comment]
@NicholasBertazzonAga I am using    
`kotlinVersion = "1.3.41"`

**Comment by NicholasBertazzonAga** [comment]
> @NicholasBertazzonAga I am using
> `kotlinVersion = "1.3.41"` // detox kotlin version

Ok, your pull request is a bit messy, there are a lot of things that are not needed, can you make another one with just the fix and nothing else? If not I'm going to publish another release soon so I will do it myself after testing

**Pull request merged**
