### PR TITLE
Setup Intent Implementation (Used for reusing cards)

### PR DESCRIPTION
**Pull request by miladebadi**

### CODE REVIEW

**Comment by miladebadi** [comment]
@NicholasBertazzonAga It is ready

**Comment by NicholasBertazzonAga** [comment]
> @NicholasBertazzonAga It is ready

Thanks, give me some time but I think I'll publish a new release with your modification as soon as today

**Comment by NicholasBertazzonAga** [comment]
@miladebadi I took a look at the JS version, and I saw that they deprecated setupIntent in favor of confirmCardSetup, I think it's more readable for newbies so I changed the method name

**Comment by NicholasBertazzonAga** [comment]
@miladebadi btw version published

**Pull request merged**
