### PR TITLE
Setup Intent Implementation (Used for reusing cards)

### PR DESCRIPTION
**Pull request by miladebadi**

### CODE REVIEW

**Comment by NicholasBertazzonAga** [comment]
Hey there, never used this API but I looked it and it seems useful for a lot of people. RIght now I don't have time to review this PR, I need to finish some things on the library in order to use it on our internal projects. When I'm done with it I'll look into this.

**Comment by miladebadi** [comment]
Perfect @NicholasBertazzonAga, really appreciate it, this PR is needed for our company use case until then We will use my fork. good luck

**Comment by NicholasBertazzonAga** [comment]
> Perfect @NicholasBertazzonAga, really appreciate it, this PR is needed for our company use-case; until then We will use my fork. good luck

Just one thing, I am aware of an Android bug, graphically the widget has a problem when used in a view with a lot of padding like, for example, a modal. I'm working on it but I don't have time now

**Comment by miladebadi** [comment]
> > Perfect @NicholasBertazzonAga, really appreciate it, this PR is needed for our company use-case; until then We will use my fork. good luck
> 
> Just one thing, I am aware of an Android bug, graphically the widget has a problem when used in a view with a lot of padding like, for example, a modal. I'm working on it but I don't have time now

Most probably we will not use Stripe native UI kit, but if we wanted to do that I will also investigate the issue, by the way thanks for your informing 👍🏻

**Comment by NicholasBertazzonAga** [comment]
> Also `paymentHandler.confirmPayment(withParams: paymentIntentParams, authenticationContext: self) ...` is deprecated now and it should change to `paymentHandler.confirmPayment(paymentIntentParams, with: self)`

Ye saw it, doing it now

**Comment by NicholasBertazzonAga** [comment]
Hey @miladebadi , can you make 1 single commit based on the latest master branch and without the bump version? I see a total a 9 commits, but there are reverts and version bump that are not useful

**Pull request closed without merging**
